import turtle

miTortugaLucera = turtle.Turtle()
miTortugaLucera.forward(50)
miTortugaLucera.left(45)
miTortugaLucera.forward(50)
miTortugaLucera.left(45)
miTortugaLucera.forward(50)
miTortugaLucera.left(45)
miTortugaLucera.forward(50)
miTortugaLucera.left(45)
miTortugaLucera.forward(50)
miTortugaLucera.left(45)
miTortugaLucera.forward(50)
miTortugaLucera.left(45)
miTortugaLucera.forward(50)
miTortugaLucera.left(45)
miTortugaLucera.forward(50)
miTortugaLucera.left(45)